<?php
/**
 * Created by PhpStorm.
 * User: mark
 * Date: 10/1/2018
 * Time: 4:47 PM
 */
namespace Angel\Auction\Model\Product;

use Magento\Framework\App\ObjectManager;
use Magento\Catalog\Api\ProductRepositoryInterface;
use Magento\Framework\Pricing\PriceCurrencyInterface;
use Magento\Framework\Serialize\Serializer\Json;
use Magento\Framework\EntityManager\MetadataPool;
use Angel\Auction\Model\Auction;

/**
 * Auction Type Model
 * @SuppressWarnings(PHPMD.TooManyFields)
 * @SuppressWarnings(PHPMD.ExcessiveClassComplexity)
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @api
 * @since 100.0.2
 */
class Type extends \Magento\Catalog\Model\Product\Type\AbstractType
{
    /**
     * Product type
     */
    const TYPE_CODE = 'auction';

    /**
     * @var \Angel\Auction\Model\AuctionFactory
     */
    protected $auctionFactory;

    /**
     * @var \Angel\Auction\Model\ResourceModel\Bid\CollectionFactory
     */
    protected $bidCollectionFactory;

    public function __construct(
        \Magento\Catalog\Model\Product\Option $catalogProductOption,
        \Magento\Eav\Model\Config $eavConfig,
        \Magento\Catalog\Model\Product\Type $catalogProductType,
        \Magento\Framework\Event\ManagerInterface $eventManager,
        \Magento\MediaStorage\Helper\File\Storage\Database $fileStorageDb,
        \Magento\Framework\Filesystem $filesystem,
        \Magento\Framework\Registry $coreRegistry,
        \Psr\Log\LoggerInterface $logger,
        ProductRepositoryInterface $productRepository,
        \Angel\Auction\Model\AuctionFactory $auctionFactory,
        $serializer = null
    ){
        parent::__construct($catalogProductOption, $eavConfig, $catalogProductType, $eventManager, $fileStorageDb, $filesystem, $coreRegistry, $logger, $productRepository, $serializer);
        $this->auctionFactory = $auctionFactory;
    }

    /**
     * Delete data specific for Bundle product type
     *
     * @param \Magento\Catalog\Model\Product $product
     * @return void
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function deleteTypeSpecificData(\Magento\Catalog\Model\Product $product)
    {
    }

    /**
     * @param \Magento\Catalog\Model\Product $product
     * @return bool
     */
    public function isSalable($product)
    {
        if ($product->getData(\Angel\Auction\Model\Auction::STATUS_FIELD) == Attribute\Source\Status::FINISHED){
            /** @var \Angel\Auction\Model\Auction $auction */
            $auction = $this->auctionFactory->create();
            $auction->init($product);
            if ($auction->isWinner()){
                return parent::isSalable($product);
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    /**
     * @param \Magento\Catalog\Model\Product $product
     * @return bool
     */
    public function isPossibleBuyFromList($product)
    {
        return false;
//        return parent::isPossibleBuyFromList($product); // TODO: Change the autogenerated stub
    }

    /**
     * @param \Magento\Framework\DataObject $buyRequest
     * @param \Magento\Catalog\Model\Product $product
     * @param string $processMode
     * @return array|string
     */
    protected function _prepareProduct(\Magento\Framework\DataObject $buyRequest, $product, $processMode)
    {
        return parent::_prepareProduct($buyRequest, $product, $processMode); // TODO: Change the autogenerated stub
    }

    /**
     * @param \Magento\Catalog\Model\Product $product
     * @return int
     */
    public function getTimeLeft($product){
        $date = new \DateTime();
        $end = new \DateTime($product->getData(Auction::END_TIME_FIELD));
        return $end->getTimestamp() - $date->getTimestamp();
    }

    /**
     * @param \Magento\Catalog\Model\Product $product
     * @return boolean
     */
    public function isProcessing($product){
        return $product->getData(Auction::STATUS_FIELD) == Attribute\Source\Status::PROCESSING;
    }
}